name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main  # Muuta tämä, jos haluat käyttää eri haaraa

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Käytä Blazor WASM -versiosi mukaista .NET:iä

      - name: Publish Blazor WASM
        run: |
            ls
            cd ./MathGame.Web
            dotnet publish -c Release -o ../release /p:BasePath=/math-game/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot

      - name: Disable Jekyll
        run: touch release/wwwroot/.nojekyll